Data redundancy for instruction serialization and storage
immux/immux pull request #33
Opened 2020-09-28 15:15 UTC by blaesus

## A. Summary

This patch adds redundancy in data storage for better data security, by adding meta data for instructions, with optional basic error correction code (**"ECC"** henceforward). It also contains necessary refactoring and bugfixes to implement the features.

## B. Current status

Before this patch, instructions are stored by concatenating their serializations.

This approach allows zero redundancy and has the two issues:–
1. If any byte is corrupt, the whole file could corrupt;
2. The log contains no meta data for the instruction bytes.

## C. Proposed improvement

We use a new concept called "instruction pack", which is the serialization form of an `instruction`.

Before this patch, 
```
instruction_pack = instruction.serialize()
```

Now, we introduce redundancies for more robust data storage and recovery.

```
Item       | bytes | Description
-----------|-------|-------------------------------------------------------------------------------
MAGIC      |   4   | Always B10CDA7A (block data), marking the beginning of an instruction pack
VER        |   1   | Version of serialization format of the pack
ECC width  |   4   | Width the the ECC section, including ECC mode byte
ECC mode   |   1   | ECC mode was used to protect data, 1 for TMR, for example
ECC main   |  vary | Main data of instruction, protected by ECC
```

![Immux-Instruction-Log](https://user-images.githubusercontent.com/233354/94641102-d9c53d00-02cf-11eb-99c1-ff971b00c4da.png)

### 1. Magic number

Instructions are prefixed with 4 constant bytes: `B1 0C DA 7A` (BLOCK DATA).

These bytes are chosen to be unlikely to appear in payload data, so that if a log is partially corrupt, we can use these magic numbers as separators to recover instructions, also if an instruction is transmitted over the networks, the receiver can more easily spot the beginning of an instruction pack.

### 2. Version

The version is an one-byte marker of the version of the serialization format, which allows software upgrade later on. Our log is append-only, and if we upgrade the software, it might have to write new instructions in new format, while keeping the old instruction in old format.

### 3. ECC width

This is a 4-byte section that records the width of the main ECC data section. This create some redundancy in parsing, so that the parser doesn't have to figure out the end by parsing. If we want to skip some instruction later on, the width information will be useful.

This create an implicit size limit for the main data, which tops at about 4GB. With TMR, this means an instruction can at most be about 1.3GB. This is deemed acceptable, because we do not expect people to store that much data in one instruction. For reference, MongoDB allows for 16MB per document and MySQL allows only about 65KB per row.

If in the future, this became an issue, we could still upgrade version for new instruction packs.

### 4. ECC Mode

Currently we have two modes: 
0x00: **Identity**, which means no transformation is used, and the data is written as is, with no error-correction potentials;
0x01: **TMR**, or triple modular redundancy, a fancy name of writing the data three times, and for each bit, we compare the three bits written and choose the majority. Naturally, it will cost 3 times the storage size, and can recover from at most 33% of bit flips.

### 5. ECC data

The instruction data encoded in the chosen error-correction mode. If identity mode is chosen, it is the data itself with no changed. This data, after decoding, is the output of `Instruction::serialize()`.

## D. DB Preferences

To facilitate use, we extracts the handling DB preferences (to `src/storage/preferences.rs`), such as the desired ECC mode. Existing preferences are also handled, for example, location of data storage, and HTTP and TCP ports.

They can be assessed with command line arguments like this, which should be self-explanatory enough.

```
cargo run --bin server --data-dir=/tmp/immux --tcp-port=8888 --http-port=2939 --ecc-mode=TMR
cargo bench --bench census90 -- 100000 20000 --ecc-mode=None
```

## E. Benchmark fix

When I benchmark this PR, I realized that it has been broken: the execution get stuck.

The cause is at commit `0fe4392c5` where we made `dev_utils.rs/launch_db_server` await HTTP and TCP threads, but not all callers of it spawn it in another thread. The benches mostly didn't.

This patch fixes this by making `launch_db_server` always spawn the server itself, so that the callers never have to.

Also, as `notified_sleep` always follows `launch_db_server`, I make `launch_db_server` to call `notified_sleep` so that the callers don't have to

## F. Byte parsing utils

Previously, our `u8_array_to_u64` and friends take fixed width bytes (for type security and performance) and it ends up with rather cumbersome callings:
```
u8_array_to_u64(&[data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7]])
```

I created a new set of functions `byte_slice_to_u64` and friends to automatically handle input width. If input is too short, it fills zero. The new calling site would just be:

```
byte_slice_to_u64(&data)
```

## F. Performance

Overall, with ECC disabled, the new codebase maintains roughly the same performance level, with a slight improvement in reading, perhaps due to data width being specified for the log parser.

### Bench with TMR ECC mode

```
Executing bench census90, with tables truncated at row 100000, aggregating 20000 operations
Initializing database in /tmp/bench_census90/
Existing test data removed
Waiting 5s...
Using preferences DBPreferences { log_dir: "/tmp/bench_census90/", ecc_mode: TMR, http_port: Some(20021), tcp_port: None }
took 5882ms to execute 20000 set_unit operations (20000/100000 done), average 0.29ms per item
took 5564ms to execute 20000 set_unit operations (40000/100000 done), average 0.28ms per item
took 5548ms to execute 20000 set_unit operations (60000/100000 done), average 0.28ms per item
took 5515ms to execute 20000 set_unit operations (80000/100000 done), average 0.28ms per item
took 5423ms to execute 20000 set_unit operations (100000/100000 done), average 0.27ms per item
Gained -2.42e-7 ms per item on average
took 6085ms to execute 20000 get_by_key operations (20000/100000 done), average 0.30ms per item
took 6341ms to execute 20000 get_by_key operations (40000/100000 done), average 0.32ms per item
took 6273ms to execute 20000 get_by_key operations (60000/100000 done), average 0.31ms per item
took 7775ms to execute 20000 get_by_key operations (80000/100000 done), average 0.39ms per item
took 5983ms to execute 20000 get_by_key operations (100000/100000 done), average 0.30ms per item
Gained 3.08e-7 ms per item on average
```

### Bench with No ECC

```
andy@carbo: ~/code/immux ecc!
 $ cargo bench --bench census90 -- 100000 20000 --ecc-mode=None                                                                    [16:51:29]
    Finished bench [optimized] target(s) in 0.15s
     Running target/release/deps/census90-9a3b655460b9e0d8

Executing bench census90, with tables truncated at row 100000, aggregating 20000 operations
Initializing database in /tmp/bench_census90/
Existing test data removed
Waiting 5s...
Using preferences DBPreferences { log_dir: "/tmp/bench_census90/", ecc_mode: Identity, http_port: Some(20021), tcp_port: None }
took 5466ms to execute 20000 set_unit operations (20000/100000 done), average 0.27ms per item
took 5371ms to execute 20000 set_unit operations (40000/100000 done), average 0.27ms per item
took 5348ms to execute 20000 set_unit operations (60000/100000 done), average 0.27ms per item
took 5334ms to execute 20000 set_unit operations (80000/100000 done), average 0.27ms per item
took 5414ms to execute 20000 set_unit operations (100000/100000 done), average 0.27ms per item
Gained -3.53e-8 ms per item on average
took 4240ms to execute 20000 get_by_key operations (20000/100000 done), average 0.21ms per item
took 4215ms to execute 20000 get_by_key operations (40000/100000 [...]

2020-09-30 11:28 UTC, poppindouble requested changes
I have some question regarding to the TMR design.

2020-09-30 11:28 UTC, poppindouble commented on src/storage/preferences.rs
> +                prefs.log_dir = PathBuf::from(arg.replace("--data-dir=", ""));
extract as constants?

2020-09-30 11:28 UTC, poppindouble commented on src/storage/preferences.rs
> +                prefs.log_dir = PathBuf::from(arg.replace("--data-dir=", ""));
same apply to below

2020-10-02 02:52 UTC, blaesus commented on src/storage/ecc.rs
> +pub trait ErrorCorrectionCodec {
Codec is the combination of a coder and a decoder:
https://en.wikipedia.org/wiki/Codec

2020-10-02 02:52 UTC, blaesus commented on src/storage/ecc.rs
> +        let encoded = codec.encode(&input);
See another comment regarding codec.

2020-10-02 02:59 UTC, blaesus commented on src/storage/ecc.rs
> +    TMR = 0x01,
Because TMR (1 byte encoded in 3 bytes) is already very costly and serves mainly an proof-of-concept. We likely want more efficient algorithms (such as Hamming(7,4) that stores 1 byte in 1.75 bytes).

2020-10-02 04:10 UTC, blaesus commented
@poppindouble Updated with named constants of serialization byte positions and command line arguments

2020-10-02 04:23 UTC, poppindouble approved these changes
Looks good

2020-10-02 11:07 UTC, merged